### ISSUE TITLE
`Set` not correctly removing duplicates

### ISSUE THREAD

**Issue by celluj34** [gastromatic/calendar-date#181]
Consider:

```js
const arr = [
  new CalendarDate(2022, 01, 01),
  new CalendarDate(2022, 01, 01)
];

const distinct = [...new Set(arr)];
```

The variable `distinct` will have two entries. Is this intended? I do understand they're objects, not primitive values.

I accomplished what I wanted by using `reduce` and `Map`, but I feel like it could be simplified somehow.

**Comment by co-sic** [comment]
Since Set only works for primitive values and object references (works the same as === operator), there is nothing we can do to make it work, since CalendarDate is an object.
But you can use a combination of map and Set like this:

```
const arr = [
  new CalendarDate(2022, 1, 1),
  new CalendarDate(2022, 1, 1)
];

const distinct = [...new Set(arr.map(v => v.toString()))].map(v => new CalendarDate(v));
console.log(distinct.length) // 1
```

**Comment by celluj34** [comment]
Yep, makes sense. I did something similar to accomplish what I did. It's unfortunate we can't override the `===` operator, that would be the best case.

Thanks for the reply!
